version: '3'

services:
  zookeeeper:
    ports:
      - 2181:2181
    image: confluent/zookeeper
    container_name: zookeeper
  kafka:
    image: confluent/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my-topic:1:3"
